# Generated by Django 4.2.2 on 2023-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='question',
            field=models.IntegerField(choices=[('1', 'Cuốn sách yêu thích nhất là gì?'), ('2', 'Cuốn sách đầu tiên mà bạn đọc?'), ('3', 'Bạn yêu thích con vật nào nhất?'), ('4', 'Món ăn yêu thích nhất của bạn là gì?')], default='1'),
        ),
    ]
