# Generated by Django 4.2.2 on 2023-08-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_users_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='question',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
