# Generated by Django 4.2.2 on 2023-08-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_users_answer_alter_users_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
