# Generated by Django 4.2.3 on 2023-07-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlbh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_name',
            new_name='name',
        ),
    ]
